### ISSUE TITLE
Windows build would need a LOT of work

### ISSUE THREAD

**Issue by horenmar** [master-keying/sharpSAT#1]
I decided to move the list of things that need fixing for Windows support into the main post

- [x] The code uses GMP
  - [x] Can be replaced by MPIR
  - [ ] vcpkg installs only C version of MPIR (slight performance problem)
- [x] The code uses `sys/time`
  - [x] Can be replaced with `<chrono>`
- [x] Uses VLA
  - [x] Should be replaceable with either `std::vector<T>`, or `make_unique<T[]>`
- [x] new/delete/free/malloc are used in a wrong manner -- found by Valgrind on Linux
- [x] `std::vector::reverse_iterator` is used in a wrong way -- VS's STL complains that it is used to decrement beyond the array used.
- [ ] `instance.cpp` uses `sys/stat.h` header.

**Comment by cernoch** [comment]
I'd say it's not that important at this point. Let's see if sharpSAT is suitable for our algorithm in the first place.

**Comment by cernoch** [comment]
But if you prefer to use Visual Studio, then feel free to go ahead. :-)

**Comment by horenmar** [comment]
The two things we found today for fixing:
1) the main TU uses `sys/` includes.
2) The library is dependent on [GMP](https://gmplib.org/)

For 2 we should probably replace the dependency with [MPIR](http://mpir.org/).

**Comment by cernoch** [comment]
Today I googled that [porting MPIR to CMake is difficult](https://github.com/wbhart/mpir/pull/215).

**Comment by horenmar** [comment]
New problems found:
* On Linux, Valgrind screams a lot -- mismatched new/deletes and bad accesses to memory
* On Windows, the STL debug integration finds a severe error in how vector::reverse_iterator is used in `Solver::BCP`.

**Comment by horenmar** [comment]
Windows should be considered fully supported now.
