### ISSUE TITLE
ComponentManager uses badly written bubble sort for sorting components

### ISSUE THREAD

**Issue by horenmar** [master-keying/sharpSAT#12]
There are two problems with it
1) It is a bubble sort. If there is a non-trivial number of components, it performs badly.
2) It is badly written -- there are no early-out checks that stop further iterations when the sorted range is already sorted.

We should instrument the relevant function and check how often it is called, how large the sorting ranges are and how badly unsorted they are (to see if early out would speed things up).

**Comment by horenmar** [comment]
I instrumented the code and after running the tests for multiple hours, I think that it isn't once called with the sorting range larger than 2 components. In other words, it is a checked swap.

**Comment by horenmar** [comment]
I finished running all the tests and collecting the information. Below is the table of range sizes and the number of times a range of that size is sorted.

| Range size | # called |
| ---------- | -------- |
| 0 | 80596851 |
| 1 | 76565473 |
| 2 | 1359639 |
| 3 | 7620 |
| 4 | 318 |
| 5 | 112 |
| 6 | 52 |
| 7 | 27 |
| 8 | 91 |
| 9 | 17 |
| 10 | 11 |
| 11 | 11 |
| 12 | 8 |
| 13 | 11 |
| 14 | 2 |
| 15 | 2 |
| 16 | 4 |
| 18 | 3 |
| 19 | 4 |
| 20 | 3 |
| 21 | 3 |
| 22 | 3 |
| 26 | 2 |
| 28 | 1 |
| 29 | 1 |
| 32 | 1 |
| 33 | 1 |
| 35 | 1 |
| 36 | 2 |
| 37 | 2 |
| 41 | 3 |
| 45 | 1 |
| 46 | 1 |
| 48 | 2 |
| 57 | 1 |
| 58 | 1 |
| 60 | 1 |
| 66 | 1 |
| 68 | 1 |
| 70 | 1 |
| 72 | 1 |
| 97 | 1 |
| 117 | 1 |
| 135 | 1 |
| 266 | 1 |
| Total under 2 | 158521963 |
| Total | 158530294 |

What this shows is that across the "easy" test suite, the sorting function is called 158M times, and almost all of the calls will need 1 swap at most. (Only ~100k of the calls need actual sorting algorithm)

Because of this, I suggest replacing the sorting with a specialized, 1 swap implementation, and a bubble sort with proper early-out check for the generic case.

**Comment by horenmar** [comment]
@cernoch The basic changes are in, what do you think about moving the 0-1 specialization to the call-site?

**Comment by cernoch** [comment]
I completely agree. Let's do this and move on. :smile:

**Comment by horenmar** [comment]
I tried moving the 0-1 check out to the caller and it made absolutely no measurable difference.
